import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'ta' | 'hi' | 'ml' | 'kn';

export interface Language {
  code: LanguageCode;
  name: string;
  nativeName: string;
}

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' }
];

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.shop': 'Shop',
    'nav.categories': 'Categories',
    'nav.search': 'Search for products, brands...',
    'nav.facing': 'Facing Language',
    'nav.wishlist': 'Wishlist',
    'nav.cart': 'Cart',
    'nav.logout': 'Sign Out',
    'nav.login': 'Sign In',
    'nav.profile': 'My Profile',
    'nav.dashboard': 'Dashboard',

    // Hero
    'hero.badge': 'AI RECOMMENDATIONS ARE ACTIVE',
    'hero.title': 'The future of e-commerce built for creators',
    'hero.subtitle': 'Explore the premium multi-vendor experience!',
    'hero.browse': 'Browse the list',
    'hero.chat': 'Chat with Aura',
    'hero.ai_best': 'AURA AI BEST RECOMMENDATION',
    'hero.view_details': 'View details',

    // Auth & General Gateways
    'auth.title': 'Secure Member Gate',
    'auth.subtitle': 'Stop into the e-commerce future. Log in dynamically to experience customer ordering tracking, product generation, and administrative platform controls.',
    'auth.email': 'Email Address',
    'auth.phone': 'Phone Number',
    'auth.password': 'Security Password',
    'auth.confirm_password': 'Confirm Security Password',
    'auth.fullname': 'Full Name',
    'auth.store_name': 'Store Name',
    'auth.verification': 'Human Verification Code',
    'auth.verification_placeholder': 'Enter visual characters',
    'auth.signup_free': 'Don\'t have an account? Sign Up Free',
    'auth.create_account': 'Create Account',
    'auth.register_profile': 'Register Profile',
    'auth.register_merchant': 'Register Merchant',
    'auth.sign_securely': 'Sign In Securely',
    'auth.sign_merchant': 'Sign In Merchant',
    'auth.already_account': 'Already have an account? Sign In Securely',
    'auth.vendor_sign': 'Want to create a vendor account? Vendor Sign In & Sign Up',
    'auth.back_customer': 'Back to Customer Login',
    'auth.verification_alt': 'Audio verification option',
    'auth.verification_refresh': 'Refresh characters',
    'auth.verification_audio': 'Play captcha audio code',

    // Vendor Dashboard
    'vendor.title': 'Merchant Portal',
    'vendor.badge_pending': 'Pending Business Verification Review',
    'vendor.subtitle': 'Complete your corporate review fields to unlock e-commerce product submissions instantly.',
    'vendor.legal_name': 'Legal Company Name',
    'vendor.description': 'Business Description',
    'vendor.reg_no': 'Company Registration Number',
    'vendor.gst_no': 'GST Tax Number',
    'vendor.biz_phone': 'Business Phone Number',
    'vendor.address': 'Corporate Office Address',
    'vendor.district': 'District',
    'vendor.state': 'State',
    'vendor.pincode': 'ZIP / Pincode',
    'vendor.lat': 'Latitude',
    'vendor.lng': 'Longitude',
    'vendor.detect_loc': 'Detect Location (Map Click / GPS API)',
    'vendor.submit_audit': 'Submit Marketplace Application',
    'vendor.application_log': 'Application Audits & History Logs',
    'vendor.active_products': 'My Catalog & Store Inventory',
    'vendor.add_product': 'Create New Product listing',
    'vendor.prod_name': 'Product Name',
    'vendor.prod_price': 'Market Price (INR)',
    'vendor.prod_stock': 'Fulfillment Units / Stock',
    'vendor.prod_desc': 'Descriptive Copy',
    'vendor.prod_cat': 'Category',
    'vendor.prod_brand': 'Brand Name',
    'vendor.prod_img': 'Image Source URLs (or Upload base64)',
    'vendor.save_prod': 'Publish Item to Public Schema',
    'vendor.orders_mgt': 'Vendor Fulfillment Queue',
    'vendor.revenue': 'Aggregated Wallet & Revenue Analytics',
    'vendor.qr_carrier': 'Fulfillment Routing QR Tools',

    // Customer / User
    'customer.dashboard': 'User Central Dashboard',
    'customer.welcome': 'Welcome, Customer Practitioner!',
    'customer.orders': 'My Orders',
    'customer.wishlist_tab': 'My Wishlist',
    'customer.addresses': 'Saved Delivery Addresses',
    'customer.reviews': 'My Experience Reviews',
    'customer.notifications': 'Alerts Box',

    // Admin Dashboard
    'admin.dashboard': 'Federated Management Hub',
    'admin.audits': 'Merchant Intake Audits',
    'admin.categories': 'Taxonomy Categories',
    'admin.brands': 'Brand Registry',
    'admin.users': 'System Accounts',
    'admin.create_adm': 'Commission Admin User',
    'admin.metrics': 'Marketplace Operations Analytics',
    'admin.schemas': 'Multi-Tenant Scheme Diagnostics',

    // Delivery
    'delivery.panel': 'Carrier Logistics Terminal',
    'delivery.scan_qr_text': 'Simulate Transit QR Scans',
    'delivery.orders_list': 'Assigned Delivery Shipments',

    // Placeholders & Helpers
    'general.loading': 'Fulfilling secure requests...',
    'general.empty': 'Zero database listings match parameters',
    'general.success': 'Fulfillment successful',
    'general.error': 'Process stopped: missing verification fields',
    'general.indian_feel': 'Bharat Open Marketplace Direct-To-Consumer',
    'home.hero_badge': 'AI RECOMMENDATIONS ARE ACTIVE',
    'home.hero_title': 'The future of e-commerce built for creators',
    'home.hero_desc': 'Explore the premium multi-vendor experience!',
    'home.explore_showcase': 'Explore Showcase Catalog',
    'home.consult_aura': 'Consult Aura AI Shopping Concierge',
    'home.ai_recs': 'Aura AI Intelligent Recommendations',
    'home.ai_match': 'AI Match Index',
    'home.add_to_cart': 'Add to Cart',
    'home.curated_categories': 'Curated Tenancy Categories',
    'home.trending_exhibits': 'Trending Marketplace Exhibits',
    'home.total_exhibiting': 'Total exhibiting',
    'home.units': 'units',
    'home.syncing': 'Syncing transactional database catalogs...',
    'home.no_matching': 'No matching products currently mapped in database registries.',
    'home.category': 'Category',
    'home.brand': 'Brand',
    'home.electronics': 'Electronics & Gadgets',
    'home.fashion': 'Traditional Apparel',
    'home.herbs': 'Organic Herbs & Spices',
    'home.grocery': 'Grocery & Pantry',
    'home.mapped_tenant': 'Dynamic Mapped Tenant',
    'cart.empty_title': 'Your Cart is Empty',
    'cart.empty_desc': 'There are no items currently added to your shopping cart.',
    'cart.empty_action': 'Browse Showcase Catalog',
    'cart.title': '1. Shop Cart',
    'cart.shipping': '2. Shipping Transit',
    'cart.payment': '3. Payment Gateway',
    'cart.billing_summary': 'Order Bill Summary',
    'cart.subtotal': 'Cart Sub-total',
    'cart.sgst': 'SGST Margins (9%)',
    'cart.cgst': 'CGST Margins (9%)',
    'cart.delivery': 'Delivery Dispatch Fees',
    'cart.free': 'FREE Code',
    'cart.due': 'Aggregate Due',
    'cart.compliance': 'Full compliance on Dynamic Multi-Tenant SGST taxation laws.',
    'cart.proceed_shipping': 'Proceed to Shipping',
    'cart.proceed_payment': 'Proceed to Payment Gate',
    'cart.confirm_transaction': 'Confirm & Unlock Waybill Order',
    'cart.select_destination': 'Select Transit Target Destination',
    'cart.note_sgst': 'Note: Mapped addresses auto-calculate SGST/CGST shipping margins across district checkpoints.',
    'cart.payment_gateway': 'Interactive Payment Gateway',
    'cart.payment_select': 'Select simulated gateway mechanism to close transaction.',
    'cart.cod_verify': 'Verify your registered mobile number on physical courier arrival.',
    'checkout.confirm': 'Order Confirmed successfully!'
  },
  ta: {
    'nav.home': 'முகப்பு',
    'nav.shop': 'கடை',
    'nav.categories': 'வகைகள்',
    'nav.search': 'தயாரிப்புகள், பிராண்டுகளைத் தேடவும்...',
    'nav.facing': 'முகப்பு மொழி',
    'nav.wishlist': 'விருப்பப்பட்டியல்',
    'nav.cart': 'கூடை',
    'nav.logout': 'வெளியேறு',
    'nav.login': 'உள்நுழைக',
    'nav.profile': 'எனது சுயவிவரம்',
    'nav.dashboard': 'டாஷ்போர்டு',

    'hero.badge': 'AI பரிந்துரைகள் செயலில் உள்ளன',
    'hero.title': 'சாண்ட்பாக்ஸர்களுக்காக உருவாக்கப்பட்ட மின்வணிகத்தின் எதிர்காலம்',
    'hero.subtitle': 'பிரீமியம் பல விற்பனையாளர் மின்வணிக அனுபவத்தை ஆராயுங்கள்!',
    'hero.browse': 'பட்டியலை உலாவுங்கள்',
    'hero.chat': 'ஆராவுடன் அரட்டையடிக்கவும்',
    'hero.ai_best': 'ஆரா AI சிறந்த பரிந்துரை',
    'hero.view_details': 'விவரங்களைக் காண்க',

    'auth.title': 'பாதுகாப்பான உறுப்பினர் வாயில்',
    'auth.subtitle': 'மின்வணிக எதிர்காலத்தில் நுழையுங்கள். வாடிக்கையாளர் ஆர்டர் டிராக்கிங், தயாரிப்பு உருவாக்கம் மற்றும் நிர்வாக மேடை கட்டுப்பாடுகளை அனுபவிக்க உள்நுழையவும்.',
    'auth.email': 'மின்னஞ்சல் முகவரி',
    'auth.phone': 'தொலைபேசி எண்',
    'auth.password': 'பாதுகாப்பு கடவுச்சொல்',
    'auth.confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'auth.fullname': 'முழு பெயர்',
    'auth.store_name': 'கடையின் பெயர்',
    'auth.verification': 'மனித சரிபார்ப்பு குறியீடு',
    'auth.verification_placeholder': 'சரிபார்ப்பு குறியீட்டை உள்ளிடவும்',
    'auth.signup_free': 'கணக்கு இல்லையா? இலவசமாக பதிவு செய்யவும்',
    'auth.create_account': 'கணக்கை உருவாக்கு',
    'auth.register_profile': 'சுயவிவரத்தை பதிவு செய்யவும்',
    'auth.register_merchant': 'வியாபாரியை பதிவு செய்யவும்',
    'auth.sign_securely': 'பாதுகாப்பாக உள்நுழையவும்',
    'auth.sign_merchant': 'விற்பனையாளர் உள்நுழைவு',
    'auth.already_account': 'ஏற்கனவே கணக்கு உள்ளதா? பாதுகாப்பாக உள்நுழையவும்',
    'auth.vendor_sign': 'விற்பனையாளர் கணக்கு உருவாக்க வேண்டுமா? விற்பனையாளர் உள்நுழைவு & பதிவு',
    'auth.back_customer': 'வாடிக்கையாளர் உள்நுழைவுக்குச் செல்லவும்',
    'auth.verification_alt': 'ஒலி சரிபார்ப்பு விருப்பம்',
    'auth.verification_refresh': 'குறியீட்டை மாற்றவும்',
    'auth.verification_audio': 'சரிபார்ப்பு ஒலியை இயக்கு',

    'vendor.title': 'விற்பனையாளர் போர்டல்',
    'vendor.badge_pending': 'வணிக சரிபார்ப்பு மதிப்பாய்வு நிலுவையில் உள்ளது',
    'vendor.subtitle': 'மின்வணிக தயாரிப்பு சமர்ப்பிப்புகளை உடனடியாகத் திறக்க உங்கள் கார்ப்பரேட் சரிபார்ப்பு புலங்களை நிரப்பவும்.',
    'vendor.legal_name': 'சட்டப்பூர்வ நிறுவனத்தின் பெயர்',
    'vendor.description': 'வணிக விளக்கம்',
    'vendor.reg_no': 'நிறுவனத்தின் பதிவு எண்',
    'vendor.gst_no': 'ஜிஎஸ்டி வரி எண்',
    'vendor.biz_phone': 'வணிக தொலைபேசி எண்',
    'vendor.address': 'கார்ப்பரேட் அலுவலக முகவரி',
    'vendor.district': 'மாவட்டம்',
    'vendor.state': 'மாநிலம்',
    'vendor.pincode': 'ஜிப் / பின்கோடு',
    'vendor.lat': 'அட்சரேகை (Latitude)',
    'vendor.lng': 'தீர்க்கரேகை (Longitude)',
    'vendor.detect_loc': 'இடத்தைக் கண்டறி (வரைபடம் அல்லது GPS)',
    'vendor.submit_audit': 'விண்ணப்பத்தை சமர்ப்பிக்கவும்',
    'vendor.application_log': 'விண்ணப்ப தணிக்கை மற்றும் வரலாற்று பதிவுகள்',
    'vendor.active_products': 'எனது தயாரிப்புகள் மற்றும் இருப்பு',
    'vendor.add_product': 'புதிய தயாரிப்பை உருவாக்கவும்',
    'vendor.prod_name': 'தயாரிப்புப் பெயர்',
    'vendor.prod_price': 'சந்தை விலை (INR)',
    'vendor.prod_stock': 'இருப்பு அலகுகள்',
    'vendor.prod_desc': 'தயாரிப்பு விவரம்',
    'vendor.prod_cat': 'வகை',
    'vendor.prod_brand': 'பிராண்ட் பெயர்',
    'vendor.prod_img': 'படத்தின் URL அல்லது சமர்ப்பிக்கவும்',
    'vendor.save_prod': 'தயாரிப்பைப் பொதுப் பட்டியலில் வெளியிடவும்',
    'vendor.orders_mgt': 'விற்பனையாளர் ஆர்டர் வரிசை',
    'vendor.revenue': 'வருவாய் பகுப்பாய்வு மற்றும் வாலட்',
    'vendor.qr_carrier': 'விற்பனை ஆர்டர் கண்காணிப்பு QR',

    'customer.dashboard': 'வாடிக்கையாளர் டாஷ்போர்டு',
    'customer.welcome': 'வருக, வாடிக்கையாளர் பயனர்!',
    'customer.orders': 'எனது ஆர்டர்கள்',
    'customer.wishlist_tab': 'எனது விருப்பப்பட்டியல்',
    'customer.addresses': 'சேமிக்கப்பட்ட விநியோக முகவரிகள்',
    'customer.reviews': 'எனது மதிப்புரைகள்',
    'customer.notifications': 'அறிவிப்புப் பெட்டி',

    'admin.dashboard': 'நிர்வாக மைய போர்டல்',
    'admin.audits': 'விற்பனையாளர் விண்ணப்ப மதிப்பாய்வு',
    'admin.categories': 'வகைகள் மேலாண்மை',
    'admin.brands': 'பிராண்டுகள் மேலாண்மை',
    'admin.users': 'முறைமை கணக்குகள்',
    'admin.create_adm': 'புதிய நிர்வாகியை உருவாக்கவும்',
    'admin.metrics': 'சந்தை பகுப்பாய்வு தரவு',
    'admin.schemas': 'பல விற்பனையாளர் திட்ட கண்டறிதல்',

    'delivery.panel': 'டெலிவரி ஊழியர் முனையம்',
    'delivery.scan_qr_text': 'QR குறியீடுகளை ஸ்கேன் செய்க',
    'delivery.orders_list': 'ஒதுக்கப்பட்ட டெலிவரிகள்',

    'general.loading': 'பாதுகாப்பான கோரிக்கைகள் பூர்த்தி செய்யப்படுகின்றன...',
    'general.empty': 'பொருந்தக்கூடிய தயாரிப்புகள் எதுவும் இல்லை',
    'general.success': 'சமர்ப்பிப்பு வெற்றிகரமாக முடிந்தது',
    'general.error': 'சரிபார்ப்பு குறியீடு தவறானது',
    'general.indian_feel': 'பாரத் திறந்த சந்தை',
    'home.hero_badge': 'AI பரிந்துரைகள் செயலில் உள்ளன',
    'home.hero_title': 'சாண்ட்பாக்ஸர்களுக்காக உருவாக்கப்படும் மின்வணிகத்தின் எதிர்காலம்',
    'home.hero_desc': 'பிரீமியம் பல விற்பனையாளர் மின்வணிக அனுபவத்தை ஆராயுங்கள்!',
    'home.explore_showcase': 'தயாரிப்புகளின் பட்டியலை ஆராய்க',
    'home.consult_aura': 'ஆரா AI நுகர்வோர் ஆலோசகரைக் கலந்தாலோசிக்கவும்',
    'home.ai_recs': 'ஆரா AI அறிவார்ந்த பரிந்துரைகள்',
    'home.ai_match': 'AI பொருத்தக் குறியீடு',
    'home.add_to_cart': 'கூடையில் சேர்க்கவும்',
    'home.curated_categories': 'கடை வகைகள்',
    'home.trending_exhibits': 'பிரபலமான தயாரிப்பு கண்காட்சிகள்',
    'home.total_exhibiting': 'மொத்த கண்காட்சி',
    'home.units': 'தயாரிப்புகள்',
    'home.syncing': 'தரவுத்தள தயாரிப்புகளை ஒத்திசைக்கிறது...',
    'home.no_matching': 'பொருந்தக்கூடிய தயாரிப்புகள் எதுவும் இல்லை.',
    'home.category': 'வகை',
    'home.brand': 'பிராண்ட்',
    'home.electronics': 'மின்னணுவியல் & கேஜெட்டுகள்',
    'home.fashion': 'பாரம்பரிய ஆடைகள்',
    'home.herbs': 'இயற்கை மூலிகைகள் & மசாலாக்கள்',
    'home.grocery': 'மளிகை & நுகர்பொருட்கள்',
    'home.mapped_tenant': 'விற்பனையாளர் தயாரிப்புகள்',
    'cart.empty_title': 'உங்களது கூடை காலியாக உள்ளது',
    'cart.empty_desc': 'தற்போது உங்களது கூடையில் தயாரிப்புகள் எதுவும் சேர்க்கப்படவில்லை.',
    'cart.empty_action': 'தயாரிப்புகளை உலாவுக',
    'cart.title': '1. ஷாப்பிங் கூடை',
    'cart.shipping': '2. கப்பல் போக்குவரத்து',
    'cart.payment': '3. கட்டண முறை சவப்பெட்டி',
    'cart.billing_summary': 'ஆர்டர் கட்டணச் சுருக்கம்',
    'cart.subtotal': 'கூடை துணை மொத்தம்',
    'cart.sgst': 'மாநில ஜிஎஸ்டி (9%)',
    'cart.cgst': 'மத்திய ஜிஎஸ்டி (9%)',
    'cart.delivery': 'விநியோக கட்டணம்',
    'cart.free': 'இலவசம்',
    'cart.due': 'மொத்தத் தொகை',
    'cart.compliance': 'மாநில மற்றும் மத்திய ஜிஎஸ்டி வரி சட்டங்களின்படி முழுமையாக இணங்குகிறது.',
    'cart.proceed_shipping': 'போக்குவரத்துக்குச் செல்லவும்',
    'cart.proceed_payment': 'கட்டண வாயிலுக்குச் செல்லவும்',
    'cart.confirm_transaction': 'ஆர்டரை உறுதிசெய்து திறக்கவும்',
    'cart.select_destination': 'விநியோக இலக்கைத் தேர்ந்தெடுக்கவும்',
    'cart.note_sgst': 'குறிப்பு: உள்ளிடப்பட்ட முகவரிகள் தானாகவே ஜிஎஸ்டி கப்பல் விளிம்புகளைக் கணக்கிடுகின்றன.',
    'cart.payment_gateway': 'ஊடாடும் கட்டண கேட்வே சாண்ட்பாக்ஸ்',
    'cart.payment_select': 'விவரங்களை இறுதி செய்ய கட்டண முறையைத் தேர்ந்தெடுக்கவும்.',
    'cart.cod_verify': 'விநியோகப் பணியாளர் வரும்போது உங்கள் தொலைபேசி எண்ணை சரிபார்க்கவும்.',
    'checkout.confirm': 'ஆர்டர் வெற்றிகரமாக உறுதிசெய்யப்பட்டது!'
  },
  hi: {
    'nav.home': 'होम',
    'nav.shop': 'दुकान',
    'nav.categories': 'श्रेणियाँ',
    'nav.search': 'उत्पादों, ब्रांडों की खोज करें...',
    'nav.facing': 'भाषा चयन',
    'nav.wishlist': 'इच्छा-सूची',
    'nav.cart': 'कार्ट',
    'nav.logout': 'साइन आउट',
    'nav.login': 'साइन इन',
    'nav.profile': 'मेरी प्रोफ़ाइल',
    'nav.dashboard': 'डैशबोर्ड',

    'hero.badge': 'एआई सिफारिशें सक्रिय हैं',
    'hero.title': 'सैंडबॉक्सर्स के लिए निर्मित ई-कॉमर्स का भविष्य',
    'hero.subtitle': 'प्रीमियम मल्टी-वेंडर अनुभव का अन्वेषण करें!',
    'hero.browse': 'सूची ब्राउज़ करें',
    'hero.chat': 'ऑरा से चैट करें',
    'hero.ai_best': 'ऑरा एआई सर्वश्रेष्ठ सिफारिश',
    'hero.view_details': 'विवरण देखें',

    'auth.title': 'सुरक्षित सदस्य द्वार',
    'auth.subtitle': 'ई-कॉमर्स भविष्य में कदम रखें। ग्राहक ऑर्डर ट्रैकिंग, उत्पाद निर्माण और प्रशासनिक नियंत्रण का अनुभव करने के लिए लॉगिन करें।',
    'auth.email': 'ईमेल पता',
    'auth.phone': 'फ़ोन नंबर',
    'auth.password': 'सुरक्षा पासवर्ड',
    'auth.confirm_password': 'पासवर्ड की पुष्टि करें',
    'auth.fullname': 'पूरा नाम',
    'auth.store_name': 'दुकान का नाम',
    'auth.verification': 'मानव सत्यापन कोड',
    'auth.verification_placeholder': 'सत्यापन कोड दर्ज करें',
    'auth.signup_free': 'खाता नहीं है? निःशुल्क पंजीकरण करें',
    'auth.create_account': 'खाता बनाएं',
    'auth.register_profile': 'प्रोफ़ाइल पंजीकृत करें',
    'auth.register_merchant': 'मर्चेंट पंजीकृत करें',
    'auth.sign_securely': 'सुरक्षित रूप से साइन इन करें',
    'auth.sign_merchant': 'विक्रेता लॉगिन',
    'auth.already_account': 'पहले से ही खाता है? सुरक्षित रूप से लॉगिन करें',
    'auth.vendor_sign': 'विक्रेता खाता बनाना चाहते हैं? विक्रेता लॉगिन और पंजीकरण',
    'auth.back_customer': 'ग्राहक लॉगिन पर वापस जाएं',
    'auth.verification_alt': 'ऑडियो सत्यापन विकल्प',
    'auth.verification_refresh': 'कोड बदलें',
    'auth.verification_audio': 'सत्यापन ऑडियो बजाएं',

    'vendor.title': 'विक्रेता पोर्टल',
    'vendor.badge_pending': 'व्यवसाय सत्यापन समीक्षा लंबित है',
    'vendor.subtitle': 'ई-कॉमर्स उत्पाद प्रस्तुतियों को तुरंत अनलॉक करने के लिए अपने व्यवसाय संबंधी विवरण भरें।',
    'vendor.legal_name': 'वैधानिक कंपनी का नाम',
    'vendor.description': 'व्यवसाय विवरण',
    'vendor.reg_no': 'कंपनी पंजीकरण संख्या',
    'vendor.gst_no': 'जीएसटी नंबर',
    'vendor.biz_phone': 'व्यवसाय फ़ोन नंबर',
    'vendor.address': 'कॉर्पोरेट कार्यालय का पता',
    'vendor.district': 'ज़िला',
    'vendor.state': 'राज्य',
    'vendor.pincode': 'पिनकोड',
    'vendor.lat': 'अक्षांश (Latitude)',
    'vendor.lng': 'देशांतर (Longitude)',
    'vendor.detect_loc': 'स्थान का पता लगाएं (मानचित्र / जीपीएस)',
    'vendor.submit_audit': 'मर्चेंट आवेदन सबमिट करें',
    'vendor.application_log': 'आवेदन ऑडिट और इतिहास लॉग',
    'vendor.active_products': 'मेरी उत्पाद सूची और इन्वेंट्री',
    'vendor.add_product': 'नया उत्पाद जोड़ें',
    'vendor.prod_name': 'उत्पाद का नाम',
    'vendor.prod_price': 'बाजार मूल्य (INR)',
    'vendor.prod_stock': 'इन्वेंट्री इकाइयाँ',
    'vendor.prod_desc': 'उत्पाद विवरण',
    'vendor.prod_cat': 'श्रेणी',
    'vendor.prod_brand': 'ब्रांड का नाम',
    'vendor.prod_img': 'छवि URL या अपलोड करें',
    'vendor.save_prod': 'उत्पाद सार्वजनिक सूची में जोड़ें',
    'vendor.orders_mgt': 'विक्रेता ऑर्डर कतार',
    'vendor.revenue': 'राजस्व विश्लेषण और वॉलेट',
    'vendor.qr_carrier': 'ऑर्डर ट्रैकिंग क्यूआर कोड',

    'customer.dashboard': 'ग्राहक डैशबोर्ड',
    'customer.welcome': 'स्वागत है, सम्मानीय ग्राहक!',
    'customer.orders': 'मेरे ऑर्डर',
    'customer.wishlist_tab': 'मेरी इच्छा-सूची',
    'customer.addresses': 'सहेजे गए वितरण पते',
    'customer.reviews': 'मेरी समीक्षाएं',
    'customer.notifications': 'सूचनाएं',

    'admin.dashboard': 'प्रशासनिक मुख्य हब',
    'admin.audits': 'विक्रेता आवेदन ऑडिट',
    'admin.categories': 'श्रेणी प्रबंधन',
    'admin.brands': 'ब्रांड प्रबंधन',
    'admin.users': 'प्रयोक्ता खाते',
    'admin.create_adm': 'नया प्रशासक बनाएं',
    'admin.metrics': 'मार्केटप्लेस विश्लेषण',
    'admin.schemas': 'मल्टी-टेनेंट डेटाबेस स्कीम',

    'delivery.panel': 'वितरण स्टाफ टर्मिनल',
    'delivery.scan_qr_text': 'वितरण क्यूआर स्कैन करें',
    'delivery.orders_list': 'सौंपे गए शिपमेंट',

    'general.loading': 'प्रक्रिया जारी है...',
    'general.empty': 'कोई उत्पाद नहीं मिला',
    'general.success': 'सफल सम्पादन',
    'general.error': 'सत्यापन कोड त्रुटि',
    'general.indian_feel': 'भारत खुला बाजार'
  },
  ml: {
    'nav.home': 'ഹോം',
    'nav.shop': 'ഷോപ്പ്',
    'nav.categories': 'വിഭാഗങ്ങൾ',
    'nav.search': 'ഉൽപ്പന്നങ്ങൾ, ബ്രാൻഡുകൾ തിരയുക...',
    'nav.facing': 'ഭാഷ തെരഞ്ഞെടുക്കുക',
    'nav.wishlist': 'പ്രിയപ്പെട്ടവ',
    'nav.cart': 'കാർട്ട്',
    'nav.logout': 'ലോഗ് ഔട്ട്',
    'nav.login': 'ലോഗ് ഇൻ',
    'nav.profile': 'എന്റെ പ്രൊഫൈൽ',
    'nav.dashboard': 'ഡാഷ്‌ബോർഡ്',

    'hero.badge': 'AI ശുപാർശകൾ സജീവമാണ്',
    'hero.title': 'സാൻഡ്‌ബോക്‌സേഴ്‌സിനായി നിർമ്മിച്ച ഇ-കൊമേഴ്‌സിന്റെ ഭാവി',
    'hero.subtitle': 'പ്രീമിയം മൾട്ടി-വെണ്ടർ അനുഭവം പര്യവേക്ഷണം ചെയ്യുക!',
    'hero.browse': 'ഉൽപ്പന്നങ്ങൾ കാണുക',
    'hero.chat': 'ഓറയുമായി ചാറ്റ് ചെയ്യുക',
    'hero.ai_best': 'ഓറ AI സ്മാർട്ട് ശുപാർശ',
    'hero.view_details': 'വിശദാംശങ്ങൾ കാണുക',

    'auth.title': 'സുരക്ഷിത മെമ്പർ ഗേറ്റ്',
    'auth.subtitle': 'ഇ-കൊമേഴ്‌സ് ഭാവിയിലേക്ക് പ്രവേശിക്കുക. കസ്റ്റമർ ഓർഡർ ട്രാക്കിംഗ്, ഉൽപ്പന്ന നിർമ്മാണം, അഡ്മിനിസ്ട്രേറ്റീവ് നിയന്ത്രണങ്ങൾ എന്നിവക്കായി പ്രവേശിക്കുക.',
    'auth.email': 'ഇമെയിൽ വിലാസം',
    'auth.phone': 'ഫോൺ നമ്പർ',
    'auth.password': 'സുരക്ഷാ പാസ്‌വേഡ്',
    'auth.confirm_password': 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    'auth.fullname': 'പൂർണ്ണമായ പേര്',
    'auth.store_name': 'കടയുടെ പേര്',
    'auth.verification': 'ഹ്യൂമൻ വെരിഫിക്കേഷൻ കോഡ്',
    'auth.verification_placeholder': 'വെരിഫിക്കേഷൻ കോഡ് നൽകുക',
    'auth.signup_free': 'അക്കൗണ്ട് ഇല്ലേ? സൗജന്യമായി രജിസ്റ്റർ ചെയ്യുക',
    'auth.create_account': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    'auth.register_profile': 'പ്രൊഫൈൽ രജിസ്റ്റർ ചെയ്യുക',
    'auth.register_merchant': 'വ്യാപാരിയായി രജിസ്റ്റർ ചെയ്യുക',
    'auth.sign_securely': 'സുരക്ഷിതമായി പ്രവേശിക്കുക',
    'auth.sign_merchant': 'വെണ്ടർ ലോഗിൻ',
    'auth.already_account': 'നിലവിൽ അക്കൗണ്ട് ഉണ്ടോ? വേഗം ലോഗിൻ ചെയ്യുക',
    'auth.vendor_sign': 'വെണ്ടർ അക്കൗണ്ട് വേണോ? ഇവിടെ ക്ലിക്ക് ചെയ്യുക',
    'auth.back_customer': 'കസ്റ്റമർ ലോഗിൻ ചെയ്യുക',
    'auth.verification_alt': 'ഓഡിയോ വഴി വെരിഫൈ ചെയ്യുക',
    'auth.verification_refresh': 'കോഡ് മാറ്റുക',
    'auth.verification_audio': 'വെരിഫിക്കേഷൻ ശബ്ദം കേൾക്കുക',

    'vendor.title': 'വെണ്ടർ പോർട്ടൽ',
    'vendor.badge_pending': 'ബിസിനസ്സ് പരിശോധന പ്രക്രിയ പുരോഗമിക്കുന്നു',
    'vendor.subtitle': 'ഇ-കൊമേഴ്‌സ് പ്രൊഡക്റ്റ് അപ്‌ലോഡ് അൺലോക്ക് ചെയ്യുന്നതിനായി താഴെയുള്ള വിവരങ്ങൾ പൂരിപ്പിക്കുക.',
    'vendor.legal_name': 'നിയമപരമായ കമ്പനിയുടെ പേര്',
    'vendor.description': 'ബിസിനസ്സ് വിവരണം',
    'vendor.reg_no': 'കമ്പനി രജിസ്ട്രേഷൻ നമ്പർ',
    'vendor.gst_no': 'ജിഎസ്ടി നമ്പർ',
    'vendor.biz_phone': 'പേഴ്സണൽ ഫോൺ നമ്പർ',
    'vendor.address': 'പ്രധാന ഓഫീസ് വിലാസം',
    'vendor.district': 'ജില്ല',
    'vendor.state': 'സംസ്ഥാനം',
    'vendor.pincode': 'പിൻകോഡ്',
    'vendor.lat': 'ലാറ്റിറ്റ്യൂഡ് (Latitude)',
    'vendor.lng': 'ലോഞ്ചിറ്റ്യൂഡ് (Longitude)',
    'vendor.detect_loc': 'സ്ഥലം കണ്ടെത്തുക (മാപ്പ് ക്ലിക്ക് ചെയ്യുക)',
    'vendor.submit_audit': 'അപേക്ഷ സമർപ്പിക്കുക',
    'vendor.application_log': 'അപേക്ഷകളും പരിശോധന ചരിത്രവും',
    'vendor.active_products': 'എന്റെ പ്രൊഡക്റ്റ് കാറ്റലോഗ്',
    'vendor.add_product': 'പുതിയ ഉൽപ്പന്നം ചേർക്കുക',
    'vendor.prod_name': 'ഉൽപ്പന്നത്തിന്റെ പേര്',
    'vendor.prod_price': 'വിപണി വില (INR)',
    'vendor.prod_stock': 'ഇൻവെന്ററി സ്റ്റോക്ക്',
    'vendor.prod_desc': 'ഉൽപ്പന്ന വിവരണം',
    'vendor.prod_cat': 'വിഭാഗം',
    'vendor.prod_brand': 'ബ്രാൻഡ് നാമം',
    'vendor.prod_img': 'ഇമേജ് URL നൽകുക',
    'vendor.save_prod': 'പൊതുവിപണിയിലേക്ക് പ്രസിദ്ധീകരിക്കുക',
    'vendor.orders_mgt': 'വെണ്ടർ ഓർഡർ ലിസ്റ്റ്',
    'vendor.revenue': 'വരുമാന വിശകലനം',
    'vendor.qr_carrier': 'ഓർഡർ ട്രാക്കിംഗ് ക്യൂആർ',

    'customer.dashboard': 'കസ്റ്റമർ ഡാഷ്‌ബോർഡ്',
    'customer.welcome': 'സ്വാഗതം, പ്രിയ ഉപഭോക്താവേ!',
    'customer.orders': 'എന്റെ ഓർഡറുകൾ',
    'customer.wishlist_tab': 'പ്രിയപ്പെട്ടവ',
    'customer.addresses': 'സേവ് ചെയ്ത വിലാസങ്ങൾ',
    'customer.reviews': 'എന്റെ റിവ്യൂകൾ',
    'customer.notifications': 'അറിയിപ്പുകൾ',

    'admin.dashboard': 'അഡ്മിനിസ്ട്രേറ്റീവ് വിംഗ്',
    'admin.audits': 'വെണ്ടർ അപേക്ഷ പരിശോധന',
    'admin.categories': 'കാറ്റഗറി മാനേജ്‌മെന്റ്',
    'admin.brands': 'ബ്രാൻഡ് മാനേജ്‌മെന്റ്',
    'admin.users': 'ലഭ്യമായ അക്കൗണ്ടുകൾ',
    'admin.create_adm': 'പുതിയ അഡ്മിനെ ചേർക്കുക',
    'admin.metrics': 'മാർക്കറ്റ് ഹിസ്റ്ററി അനലിറ്റിക്സ്',
    'admin.schemas': 'മൾട്ടി-വെണ്ടർ ഡാറ്റാബേസ് സ്കീമുകൾ',

    'delivery.panel': 'ഡെലിവറി സ്റ്റാഫ് കൺസോൾ',
    'delivery.scan_qr_text': 'ഡെലിവറി ക്യൂആർ സ്കാൻ ചെയ്യുക',
    'delivery.orders_list': 'ഏൽപ്പിച്ച ഷിപ്മെന്റുകൾ',

    'general.loading': 'വേഗത്തിൽ അപ്‌ലോഡ് ചെയ്യുന്നു...',
    'general.empty': 'ഉൽപ്പന്നങ്ങൾ ഒന്നും കണ്ടെത്താനായില്ല',
    'general.success': 'വിജയകരമായി പൂർത്തിയാക്കി',
    'general.error': 'കോഡ് തെറ്റാണ്',
    'general.indian_feel': 'ഭാരത് ഓപ്പൺ മാർക്കറ്റ് പ്ലേസ്',
    'home.hero_badge': 'AI ശുപാർശകൾ സജീവമാണ്',
    'home.hero_title': 'സാൻഡ്‌ബോക്‌സേഴ്‌സിനായി നിർമ്മിച്ച ഇ-കൊമേഴ്‌സിന്റെ ഭാവി',
    'home.hero_desc': 'മൾട്ടി-വെണ്ടർ അനുഭവം പര്യവേക്ഷണം ചെയ്യുക!',
    'home.explore_showcase': 'ഷോകേസ് കാറ്റലോഗ് കാണുക',
    'home.consult_aura': 'ഓറ AI ഷോപ്പിംഗ് അസിസ്റ്റന്റുമായി സംസാരിക്കുക',
    'home.ai_recs': 'ഓറ AI സ്മാർട്ട് ശുപാർശകൾ',
    'home.ai_match': 'AI മാച്ച് ഇൻഡെക്സ്',
    'home.add_to_cart': 'കാർട്ടിലേക്ക് ചേർക്കുക',
    'home.curated_categories': 'ലഭ്യമായ പ്രധാന বিভাগങ്ങൾ',
    'home.trending_exhibits': 'ട്രെൻഡിംഗ് ഉൽപ്പന്നങ്ങൾ',
    'home.total_exhibiting': 'ആകെ ലഭ്യമായവ',
    'home.units': 'എണ്ണം',
    'home.syncing': 'ഡാറ്റാബേസ് ഉൽപ്പന്നങ്ങൾ ലഭ്യമാക്കുന്നു...',
    'home.no_matching': 'തിരഞ്ഞെടുത്ത വിഭാഗത്തിൽ ഉൽപ്പന്നങ്ങൾ ഒന്നും കണ്ടെത്താനായില്ല.',
    'home.category': 'വിഭാഗം',
    'home.brand': 'ബ്രാൻഡ്',
    'home.electronics': 'ഇലക്ട്രോണിക്സ് & ഗാഡ്‌ജെറ്റുകൾ',
    'home.fashion': 'പരമ്പരാഗത വസ്ത്രങ്ങൾ',
    'home.herbs': 'ജൈവ ഔഷധങ്ങളും സുഗന്ധവ്യഞ്ജനങ്ങളും',
    'home.grocery': 'പലചരക്ക് സാധനങ്ങൾ',
    'home.mapped_tenant': 'രജിസ്റ്റർ ചെയ്ത വെണ്ടർ പ്രൊഡക്റ്റുകൾ',
    'cart.empty_title': 'നിങ്ങളുടെ കാർട്ട് കാലിയാണ്',
    'cart.empty_desc': 'നിങ്ങളുടെ കാർട്ടിൽ ഇപ്പോൾ ഉൽപ്പന്നങ്ങൾ ഒന്നും തന്നെയില്ല.',
    'cart.empty_action': 'ഉൽപ്പന്നങ്ങൾ കാണുക',
    'cart.title': '1. ഷോപ്പ് കാർട്ട്',
    'cart.shipping': '2. ഡെലിവറി വിലാസം',
    'cart.payment': '3. പേമെന്റ് രീതി',
    'cart.billing_summary': 'ബിൽ വിവരങ്ങൾ',
    'cart.subtotal': 'ഉൽപ്പന്നങ്ങളുടെ വില',
    'cart.sgst': 'സംസ്ഥാന ജിഎസ്ടി (9%)',
    'cart.cgst': 'കേന്ദ്ര ജിഎസ്ടി (9%)',
    'cart.delivery': 'ഡെലിവറി ചാർജ്',
    'cart.free': 'സൗജന്യം',
    'cart.due': 'ആകെ അടയ്ക്കേണ്ട തുക',
    'cart.compliance': 'ജിഎസ്ടി നികുതി നിയമങ്ങൾ പൂർണ്ണമായും പാലിക്കുന്നുണ്ട്.',
    'cart.proceed_shipping': 'വിലാസം തിരഞ്ഞെടുക്കുക',
    'cart.proceed_payment': 'പേമെന്റിലേക്ക് തുടരുക',
    'cart.confirm_transaction': 'ഓർഡർ സ്ഥിരീകരിക്കുക',
    'cart.select_destination': 'ഡെലിവറി വിലാസം തിരഞ്ഞെടുക്കുക',
    'cart.note_sgst': 'ശ്രദ്ധിക്കുക: നൽകിയിരിക്കുന്ന വിലാസത്തിന് അനുയോജ്യമായ ജിഎസ്ടി നികുതികൾ സ്വയമേവ കണക്കാക്കപ്പെടുന്നതാണ്.',
    'cart.payment_gateway': 'പേമെന്റ് ഗേറ്റ്‌വേ സാൻഡ്‌ബോക്‌സ്',
    'cart.payment_select': 'ഇടപാട് പൂർത്തിയാക്കാൻ പേമെന്റ് രീതി തിരഞ്ഞെടുക്കുക.',
    'cart.cod_verify': 'ഡെലിവറി ലഭ്യമാകുമ്പോൾ രജിസ്റ്റർ ചെയ്ത മൊബൈൽ നമ്പർ സ്ഥിരീകരിക്കുക.',
    'checkout.confirm': 'ഓർഡർ വിജയകരമായി സ്ഥിരീകരിച്ചു!'
  },
  kn: {
    'nav.home': 'ಮುಖಪುಟ',
    'nav.shop': 'ಅಂಗಡಿ',
    'nav.categories': 'ವರ್ಗಗಳು',
    'nav.search': 'ಉತ್ಪನ್ನಗಳು, ಬ್ರ್ಯಾಂಡ್‌ಗಳನ್ನು ಹುಡುಕಿ...',
    'nav.facing': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    'nav.wishlist': 'ನಿರೀಕ್ಷಿತ ಪಟ್ಟಿ',
    'nav.cart': 'ಕಾರ್ಟ್',
    'nav.logout': 'ಸೈನ್ ಔಟ್',
    'nav.login': 'ಸೈನ್ ಇನ್',
    'nav.profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',

    'hero.badge': 'AI ಶಿಫಾರಸುಗಳು ಸಕ್ರಿಯವಾಗಿವೆ',
    'hero.title': 'ಸ್ಯಾಂಡ್‌ಬಾಕ್ಸ್‌ಗಳಿಗಾಗಿ ನಿರ್ಮಿಸಲಾದ ಇ-ಕಾಮರ್ಸ್‌ನ ಭವಿಷ್ಯ',
    'hero.subtitle': 'ಪ್ರೀಮಿಯಂ ಮಲ್ಟಿ-ವೆಂಡರ್ ಇ-ಕಾಮರ್ಸ್ ಅನುಭವವನ್ನು ಅನ್ವೇಷಿಸಿ!',
    'hero.browse': 'ಪಟ್ಟಿಯನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
    'hero.chat': 'ಆರಾ ಅವರೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ',
    'hero.ai_best': 'ಆರಾ AI ಅತ್ಯುತ್ತಮ ಶಿಫಾರಸು',
    'hero.view_details': 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',

    'auth.title': 'ಸುರಕ್ಷಿತ ಸದಸ್ಯ ಗೇಟ್',
    'auth.subtitle': 'ಇ-ಕಾಮರ್ಸ್ ಭವಿಷ್ಯಕ್ಕೆ ಹೆಜ್ಜೆ ಇರಿಸಿ. ಗ್ರಾಹಕರ ಆರ್ಡರ್ ಟ್ರ್ಯಾಕಿಂಗ್, ಉತ್ಪನ್ನ ಸೃಷ್ಟಿ ಮತ್ತು ಅಡ್ಮಿನ್ ನಿಯಂತ್ರಣಗಳಿಗೆ ಲಾಗಿನ್ ಮಾಡಿ.',
    'auth.email': 'ಇಮೇಲ್ ವಿಳಾಸ',
    'auth.phone': 'ಫೋನ್ ಸಂಖ್ಯೆ',
    'auth.password': 'ಭದ್ರತಾ ಪಾಸ್‌ವರ್ಡ್',
    'auth.confirm_password': 'ಪಾಸ್‌ವರ್ಡ್ ಅನ್ನು ಖಚಿತಪಡಿಸಿ',
    'auth.fullname': 'ಪೂರ್ಣ ಹೆಸರು',
    'auth.store_name': 'ಅಂಗಡಿಯ ಹೆಸರು',
    'auth.verification': 'ಮಾನವ ಪರಿಶೀಲನಾ ಕೋಡ್',
    'auth.verification_placeholder': 'ಪರಿಶೀಲನಾ ಕೋಡ್ ನಮೂದಿಸಿ',
    'auth.signup_free': 'ಖಾತೆ ಇಲ್ಲವೇ? ಉಚಿತವಾಗಿ ನೋಂದಾಯಿಸಿ',
    'auth.create_account': 'ಖಾತೆಯನ್ನು ರಚಿಸಿ',
    'auth.register_profile': 'ಪ್ರೊಫೈಲ್ ನೋಂದಾಯಿಸಿ',
    'auth.register_merchant': 'ವ್ಯಾಪಾರಿಯನ್ನು ನೋಂದಾಯಿಸಿ',
    'auth.sign_securely': 'ಸುರಕ್ಷಿತವಾಗಿ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'auth.sign_merchant': 'ಮಾರಾಟಗಾರರ ಲಾಗಿನ್',
    'auth.already_account': 'ಖಾತೆ ಈಗಾಗಲೇ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ',
    'auth.vendor_sign': 'ಮಾರಾಟಗಾರರ ಖಾತೆಯನ್ನು ರಚಿಸಬೇಕೆ? ಇಲ್ಲಿ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'auth.back_customer': 'ಗ್ರಾಹಕರ ಲಾಗಿನ್‌ಗೆ ಹಿಂತಿರುಗಿ',
    'auth.verification_alt': 'ಆಡಿಯೋ ಪರಿಶೀಲನೆ ಆಯ್ಕೆ',
    'auth.verification_refresh': 'ಕೋಡ್ ಬದಲಾಯಿಸಿ',
    'auth.verification_audio': 'ಕೋಡ್ ಆಡಿಯೋ ಪ್ಲೇ ಮಾಡಿ',

    'vendor.title': 'ಮಾರಾಟಗಾರರ ಪೋರ್ಟಲ್',
    'vendor.badge_pending': 'ಬಿಜಿನೆಸ್ ಪರಿಶೀಲನೆ ಬಾಕಿ ಇದೆ',
    'vendor.subtitle': 'ಉತ್ಪನ್ನಗಳನ್ನು ಲಿಸ್ಟ್ ಮಾಡಲು ನಿಮ್ಮ ಬಿಜಿನೆಸ್ ವಿವರಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ ಬಾಕಿ ಅನುಮೋದನೆಯನ್ನು ಪಡೆದುಕೊಳ್ಳಿ.',
    'vendor.legal_name': 'ಕಾನೂನು ಸಂಸ್ಥೆಯ ಹೆಸರು',
    'vendor.description': 'ವ್ಯಾಪಾರ ವಿವರಣೆ',
    'vendor.reg_no': 'ಸಂಸ್ಥೆಯ ನೋಂದಣಿ ಸಂಖ್ಯೆ',
    'vendor.gst_no': 'ಜಿಎಸ್ಟಿ ಸಂಖ್ಯೆ',
    'vendor.biz_phone': 'ವ್ಯಾಪಾರ ಫೋನ್ ಸಂಖ್ಯೆ',
    'vendor.address': 'ಕಾರ್ಪೊರೇಟ್ ವಾಸ ವಿಳಾಸ',
    'vendor.district': 'ಜಿಲ್ಲೆ',
    'vendor.state': 'ರಾಜ್ಯ',
    'vendor.pincode': 'ಪಿನ್‌ಕೋಡ್',
    'vendor.lat': 'ಅಕ್ಷಾಂಶ (Latitude)',
    'vendor.lng': 'ರೇಖಾಂಶ (Longitude)',
    'vendor.detect_loc': 'ಸ್ಥಳ ಪತ್ತೆ ಮಾಡಿ (ನಕ್ಷೆ/ಜಿಪಿಎಸ್)',
    'vendor.submit_audit': 'ಅರ್ಜಿಯನ್ನು ಸಲ್ಲಿಸಿ',
    'vendor.application_log': 'ಅರ್ಜಿಗಳು ಮತ್ತು ಪರಿಶೀಲನೆ ಇತಿಹಾಸ',
    'vendor.active_products': 'ನನ್ನ ಉತ್ಪನ್ನಗಳು ಮತ್ತು ಸ್ಟಾಕ್',
    'vendor.add_product': 'ಹೊಸ ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಿ',
    'vendor.prod_name': 'ಉತ್ಪನ್ನದ ಹೆಸರು',
    'vendor.prod_price': 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆ (INR)',
    'vendor.prod_stock': 'ದಾಸ್ತಾನು ಪ್ರಮಾಣ',
    'vendor.prod_desc': 'ಉತ್ಪನ್ನದ ವಿವರ',
    'vendor.prod_cat': 'ವರ್ಗ',
    'vendor.prod_brand': 'ಬ್ರಾಂಡ್ ಹೆಸರು',
    'vendor.prod_img': 'ಚಿತ್ರದ ಲಿಂಕ್ ಅಥವಾ ಅಪ್‌ಲೋಡ್',
    'vendor.save_prod': 'ಉತ್ಪನ್ನವನ್ನು ಸಾರ್ವಜನಿಕ ಪಟ್ಟಿಗೆ ಸೇರಿಸಿ',
    'vendor.orders_mgt': 'ಮಾರಾಟಗಾರರ ಆರ್ಡರ್ ಕ್ಯೂ',
    'vendor.revenue': 'ಆದಾಯ ವಿಶ್ಲೇಷಣೆ',
    'vendor.qr_carrier': 'ಆರ್ಡರ್ ಟ್ರ್ಯಾಕಿಂಗ್ ಕ್ಯೂಆರ್',

    'customer.dashboard': 'ಗ್ರಾಹಕರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'customer.welcome': 'ಸ್ವಾಗತ, ಗ್ರಾಹಕ ಬಳಕೆದಾರರೇ!',
    'customer.orders': 'ನನ್ನ ಆರ್ಡರ್‌ಗಳು',
    'customer.wishlist_tab': 'ನನ್ನ ನಿರೀಕ್ಷಿತ ಪಟ್ಟಿ',
    'customer.addresses': 'ಉಳಿಸಿದ ವಿತರಣಾ ವಿಳಾಸಗಳು',
    'customer.reviews': 'ನನ್ನ ವಿಮರ್ಶೆಗಳು',
    'customer.notifications': 'ಅಧಿಸೂಚನೆಗಳು',

    'admin.dashboard': 'ಆಡಳಿತ ಮಂಡಳಿ',
    'admin.audits': 'ಮಾರಾಟಗಾರರ ಅರ್ಜಿಗಳ ಪರಿಶೀಲನೆ',
    'admin.categories': 'ವರ್ಗಗಳ ನಿರ್ವಹಣೆ',
    'admin.brands': 'ಬ್ರ್ಯಾಂಡ್ ನಿರ್ವಹಣೆ',
    'admin.users': 'ಖಾತೆಗಳ ಪಟ್ಟಿ',
    'admin.create_adm': 'ಹೊಸ ಅಡ್ಮಿನ್ ಸೃಷ್ಟಿಸಿ',
    'admin.metrics': 'ಮಾರುಕಟ್ಟೆ ಆದಾಯ ವಿವರಗಳು',
    'admin.schemas': 'ಮಲ್ಟಿ-ವೆಂಡರ್ ಡೇಟಾಬೇಸ್ ಸ್ಕೀಮಾ ಮತ್ತು ವಿಶ್ಲೇಷಣೆ',

    'delivery.panel': 'ಡೆಲಿವರಿ ಸಿಬ್ಬಂದಿ ಪೋರ್ಟಲ್',
    'delivery.scan_qr_text': 'ಡೆಲಿವರಿ ಕ್ಯೂಆರ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    'delivery.orders_list': 'ನಿಯೋಜಿತ ಡೆಲಿವರಿಗಳು',

    'general.loading': 'ವೇಗವಾಗಿ ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'general.empty': 'ಯಾವುದೇ ಉತ್ಪನ್ನಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'general.success': 'ಯಶಸ್ವಿಯಾಗಿ ಪೂರ್ಣಗೊಂಡಿದೆ',
    'general.error': 'ಕೋಡ್ ತಪ್ಪಾಗಿದೆ',
    'general.indian_feel': 'ಭಾರತ ಮುಕ್ತ ಮಾರುಕಟ್ಟೆ ಭವನ'
  }
};

interface LanguageContextProps {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('facing_language');
    return (saved as LanguageCode) || 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('facing_language', lang);
  };

  const t = (key: string): string => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS['en'];
    return langDict[key] || TRANSLATIONS['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
